### ISSUE TITLE
Build for macOS 10.14 errors

### ISSUE THREAD

**Issue by ashshaosh** [dfranx/SHADERed#81]
mcOS 10.14.6, XCode updated to 11.3.1

I do:
git clone https://github.com/dfranx/SHADERed.git
git submodule update --init --recursive
cd SHADERed
mkdir build
cd build
cmake ../
make -j8

And get: 
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/SHADERed.dir/GUIManager.cpp.o] Error 1
2 warnings and 1 error generated.
3 warnings and 1 error generated.
make[2]: *** [CMakeFiles/SHADERed.dir/InterfaceManager.cpp.o] Error 1
make[2]: *** [CMakeFiles/SHADERed.dir/EditorEngine.cpp.o] Error 1
make[1]: *** [CMakeFiles/SHADERed.dir/all] Error 2
make: *** [all] Error 2

Many errors like "... /SHADERed/GUIManager.cpp:1042:69: error: 'string' is unavailable: introduced in macOS 10.15" or "'~path' is unavailable"

Here is CMakeOutput log
[CMakeOutput.log](https://github.com/dfranx/SHADERed/files/4302876/CMakeOutput.log)

Maybe I'm doing something wrong? It's necessary to update macOS to 10.15?

**Comment by xinaesthete** [comment]
Yeah, I just upgraded to 10.15 and it now builds and runs ok.  I think it's to do with C++17 standard library not being supported on older systems.

**Comment by Calinou** [comment]
It should definitely be possible to target older versions while building C++17 code, but you may need to build on macOS 10.15 indeed.

**Comment by xinaesthete** [comment]
I have an old-ish iMac running 10.13 I think. I might see if I can get a build running on there at some point.

**Comment by kimown** [comment]
```
fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
3 warnings and 1 error generated.
make[2]: *** [CMakeFiles/SHADERed.dir/src/SHADERed/GUIManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/SHADERed.dir/all] Error 2
make: *** [all] Error 2

```

build fails in 10.14 too.
