### ISSUE TITLE
Cant Compile on Elementary OS 5.1.3

### ISSUE THREAD

**Issue by Hedronmx** [dfranx/SHADERed#96]
```
In file included from /home/carlos/SHADERed/main.cpp:7:0:
/home/carlos/SHADERed/src/SHADERed/Objects/CommandLineOptionParser.h:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/SHADERed.dir/build.make:62: recipe for target 'CMakeFiles/SHADERed.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/SHADERed.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/SHADERed.dir/all' failed
make[1]: *** [CMakeFiles/SHADERed.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

I get that error

**Comment by dfranx** [comment]
What's your compilers version? Does it support C++17?

**Comment by Hedronmx** [comment]
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 I suppose.... Not sure if it compiles c++ 17

**Comment by Calinou** [comment]
According to https://en.cppreference.com/w/cpp/compiler_support, support for C++ `<filesystem>` was added in GCC 8 (libstdc++ 8, to be precise).

You'll need to upgrade your Linux distribution (preferably) or use a PPA to upgrade the GCC version on your system.
